// Mocks generated by Mockito 5.4.6 from annotations
// in demo_test/test/features/tasks/data/repositories/task_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:demo_test/features/tasks/data/datasources/task_local_datasource.dart'
    as _i3;
import 'package:demo_test/features/tasks/data/models/task_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaskModel_0 extends _i1.SmartFake implements _i2.TaskModel {
  _FakeTaskModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskLocalDatasource extends _i1.Mock
    implements _i3.TaskLocalDatasource {
  MockTaskLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.TaskModel>> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<_i2.TaskModel?> getTaskById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [id]),
            returnValue: _i4.Future<_i2.TaskModel?>.value(),
          )
          as _i4.Future<_i2.TaskModel?>);

  @override
  _i4.Future<_i2.TaskModel> saveTask(_i2.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#saveTask, [task]),
            returnValue: _i4.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(this, Invocation.method(#saveTask, [task])),
            ),
          )
          as _i4.Future<_i2.TaskModel>);

  @override
  _i4.Future<void> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
